### ISSUE TITLE
difference in _date function between 1.0.0 and 1.1.1

### ISSUE THREAD

**Issue by jeffehobbs** [egorsmkv/rfeed#2]
In the original 1.0.0 version of rfeed, the _date function takes two arguments:

https://github.com/svpino/rfeed/blob/master/rfeed.py#L37

In the 1.1.1 fork, it takes one:

https://github.com/egorsmkv/rfeed/blob/master/rfeed/rfeed.py#L47

When I call _date in 1.1.1, I get this error:

`Traceback (most recent call last):
  File "app_rfeed.py", line 129, in <module>
    main()
  File "app_rfeed.py", line 113, in main
    fout.write(feed.rss())
  File "/home/jeff/ytpod/venv/lib/python3.7/site-packages/rfeed/rfeed.py", line 799, in rss
    self.publish(handler)
  File "/home/jeff/ytpod/venv/lib/python3.7/site-packages/rfeed/rfeed.py", line 848, in publish
    item.publish(self.handler)
  File "/home/jeff/ytpod/venv/lib/python3.7/site-packages/rfeed/rfeed.py", line 699, in publish
    self._write_element("pubDate", self._date(self.pubDate))
  File "/home/jeff/ytpod/venv/lib/python3.7/site-packages/rfeed/rfeed.py", line 69, in _date
    ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][date.weekday()], date.day,
AttributeError: 'str' object has no attribute 'weekday'`

Which function is correct?

**Comment by jeffehobbs** [comment]
Whoops, my bad. Never mind, figured it out!
